### ISSUE TITLE
Create Single Exercise View (SingleExercise.js)

### ISSUE THREAD

**Issue by rscoville29** [2206-capstone-lifters/lift-the-world#12]
-more details about the exercise
-recommended reps/sets/rest times/weight (based on difficulty)
-beginner/intermediate/advanced
-equipment requirements
-tips/tricks
-video (extra feature)
-user input: weight, reps, sets
previous time(s) workout was done: date, weight, reps, sets, how difficult

**Comment by rscoville29** [comment]
Only working in SingleWorkout.js

**Comment by nickyjhong** [comment]
I tried going to your branches and trying from main but it kept giving me errors. I changed some apis/stores/SingleExercise.js on the workouts branch.
SingleExercise.js now changes based on the params id but I haven't added the other details in yet besides the name and add to workout button.
